### ISSUE TITLE
Slider for a Number component can display wrong position on page load

### ISSUE THREAD

**Issue by anatoly-savchenkov** [esphome/esphome-webserver#11]
Testing changes for the Climate support I found that there are some strange things with sliders. Slider position can be wrong on page load while Inspector shows a correct value. These problems are somehow connected to the Number component and range of values.Try this YAML:
```
web_server:
  port: 80
  version: 2
  local: true

number:
  - platform: template
    name: qq
    min_value: 0
    max_value: 1000
    step: 1
    optimistic: true
    restore_value: true
    entity_category: config
    unit_of_measurement: '%'
    mode: slider
```

and you'll see this:
![bad_qq](https://user-images.githubusercontent.com/48646998/184035869-3d4cbba8-7f2e-4376-9047-cd2c4e90e849.png) If changes to the number are done (locally or remotely) the slides works ok. Slider also works ok even on page load with Safari (but not with Chrome or Firefox). Slider also shows the right value after load if max_value is changed to 100 in the YAML above.

While presence of a Number component triggers the problem, misbehaving slider can be one related to another component, like on this screenshot:
![bad_slider](https://user-images.githubusercontent.com/48646998/184037884-e647d77a-1293-456e-b207-3509ecc06614.png)

This is definitely something in the browser code, network sniffer shows valid data being sent from ESPHome. And since different behavior is observed between browsers I suspect some non/poorly portable constructions. But I have no clue how to isolate this and need advises / help.
