### ISSUE TITLE
v3: Duplicate Sensor Names Cause Only One Sensor Output to be Displayed

### ISSUE THREAD

**Issue by madurapa** [esphome/esphome-webserver#122]
When adding sensors to the YAML configuration as shown below, only one sensor output is displayed because both sensors use the same name, `Voltage`.

```
sensor:
  - platform: pipsolar
    pipsolar_id: ${pipsolar_id}
    grid_voltage:
      id: ${name}_${inverter}_grid_voltage
      name: "Voltage"
      web_server_sorting_weight: 0.01
      accuracy_decimals: 0
      icon: mdi:flash
    ac_output_voltage:
      id: ${name}_${inverter}_ac_output_voltage
      name: "Voltage"
      web_server_sorting_weight: 1.01
      accuracy_decimals: 0
      icon: mdi:flash
```
