### ISSUE TITLE
Online indicator and uptime not refreshed for stamps3

### ISSUE THREAD

**Issue by djrm05** [esphome/esphome-webserver#124]
I have a couple of M5stack stampS3 running ESPHome 2024.9.1 and both the online indicator and uptime are not being refreshed automatically none in v2 or v3 component version when the framework type is set to esp-idf
```
esp32:
  board: esp32-s3-devkitc-1 #m5stack-stamps3
  framework:
    type: esp-idf

```
however changing the type to arduino, seems to work.  I
```
esp32:
  board: esp32-s3-devkitc-1 #m5stack-stamps3
  framework:
    type: arduino
    version: latest
```
I have tried to search by this and not found any information, so may I know if this is an known issue or if this could be fixed somehow?

Thanks!
