### ISSUE TITLE
webserver frontend JS does not encode URLs

### ISSUE THREAD

**Issue by Habbie** [esphome/esphome-webserver#13]
I have this config snippet:

```
select:
  - platform: template
    name: "Button pressed"
    optimistic: true
    options:
      - none
      - seek+
      - seek-
      - vol+
      - vol-
    initial_option: none
    id: choice
```

which gives me a nice dropdown in `web_server:`. Picking `none`, `seek-` or `vol-` works, but picking `seek+` yields `[20:01:08][W][select:111]: 'Button pressed' - Option seek  is not a valid option` - note the double space in there!

The URL POSTed to is `http://radio.local/select/button_pressed/set?option=seek+` while it should be `?option=seek%2b`

I did not check if there are any other characters that would need treatment, but I suspect (I'm not a JS person at all) that a simple function for this exists.
