### ISSUE TITLE
Bug: Toggle state doesn't always update when switch state does

### ISSUE THREAD

**Issue by Junikorn** [esphome/esphome-webserver#6]
In V2 version of UI sometimes when using automations state updates but toggle component does not reflect it (while text status always does).
Possible culprit: https://github.com/esphome/esphome-webserver/blob/d918bc1da205f6af27b985407df7de252d1c6f02/v2/esp-entity-table.ts#L120
I would fix it and submit a merge request, but I do not write in LitElements and I am not entirely sure that I understand how you manage state.

I would be very grateful for a fix.
Kind regards

**Comment by Junikorn** [comment]
After digging into the topic it seems that state gets updated but checkbox `checked` property in DOM does not. Simplyfying logic to have only one truth source sadly didn't help as `checked` has been properly set. I have no idea how Lit sets DOM properties so that is as far as I get with this. Failing line is https://github.com/esphome/esphome-webserver/blob/d918bc1da205f6af27b985407df7de252d1c6f02/v2/esp-switch.ts#L45

**Comment by alexyao2015** [comment]
I noticed this as well. Not very familiar with litelement or frontend, but it does appear that simply adding a callback to reflect the checkbox when state changes should fix this. https://lit.dev/docs/v1/components/properties/#observed-attributes

**Comment by wilberforce** [comment]
Please post the yaml you are using.

Is there an easy way to reproduce the problem?

**Comment by alexyao2015** [comment]
I'm in the process of creating a pr to fix this. It should be done soon.

**Comment by alexyao2015** [comment]
The root cause of this is that the ui uses an optimistic state for the toggles rather than relying on state pushes from the device.

**Comment by Junikorn** [comment]
> Please post the yaml you are using.
> 
> Is there an easy way to reproduce the problem?

This should be sufficient to reproduce the problem:
```
switch:
  - platform: gpio
    pin: GPIO17
    id: relay_2
    on_turn_on:
      then:
        - switch.turn_off: relay_3
  - platform: gpio
    pin: GPIO05
    id: relay_3
    on_turn_on:
      then:
        - switch.turn_off: relay_2
    ```
